config/routes.rb
Rails.application.routes.draw do
  # get 'departments/name:string'
  root "students#index"
  # get "students" => "students#index"
  # get "students/:id" => "students#show", as: "student"
  # delete "students/:id" => "students#destroy" 
  # get "students/:id/edit" => "students#edit", as: "edit_student"
  # patch "students/:id" => "students#update"
  resources :students
  resources :departments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :students
	default_scope {where('is_deleted = false')}
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :department
	default_scope {joins(:department).where('departments.is_deleted = false')}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
	def index
		@departments = Department.all
	end

	def show
		@department = Department.find(params[:id])
	end

	def edit
		@department = Department.find(params[:id])
	end

	def update
		@department = Department.find(params[:id])
		if @department.update(department_params)
			flash[:notice] = "Department is updated"
			redirect_to @department
		else
			render :edit
		end
	end

	def new
		@department = Department.new
	end

	def create
		@department =Department.new(department_params)
		if @department.save
			redirect_to @department
		else
			render:new
		end
	end

	def destroy
		@department = Department.find(params[:id])
		if @department.update(is_deleted: true)
			redirect_to departments_path
		# else 
			# redirect_to department_path
		end
		
		
	end

	private

	def department_params
		params.require(:department).permit(:name)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
	 	@students= Student.all
	end

	def show
		@student= Student.find(params[:id])
	end

	def edit
		@student= Student.find(params[:id])
	end

	def update
		@student= Student.find(params[:id])
		if @student.update(student_params)
			flash[:notice] = "Student is updated"
			redirect_to @student
		else
			render :edit
		end
	end

	def new
		@student= Student.new	
	end

	def create
		@student= Student.new(student_params)
		if @student.save
		 redirect_to @student
		else
			render:new		
		end
	end

	def destroy
		@student= Student.find(params[:id])
		@student.destroy
		redirect_to root_path
	end

	private
	def student_params
		params.require(:student).permit(:name, :gender, :address, :department_id)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/student_lists_helper.rb
module StudentListsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |d|%>
 <div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class= "row">
      <div class="col-md-3">
        <%= d.label :name , class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= d.text_field :name, autofocus: true , class: "form-control" %>
      </div>
    </div>
    </br>
    <%= d.submit"Save",class: "btn btn-success"  %> | 
  <%=link_to"Cancel", root_path%>    
<% end %>

app/views/departments/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/students">Student Management</a>
    <ul class="nav navbar-nav">
      </li>
      <li><%=link_to"Add New Department",new_department_path%></a></li>
      </ul>
    </ul>
  </div>
</nav>
  

  

app/views/departments/edit.html.erb
<h1>Editng Department</h1>
 <%= render 'form'%>

app/views/departments/index.html.erb
<h1>All Department for Student</h1>

<table>
  <tr>
    <th>Department Name</th>
    <th>Setting</th>
  </tr>
  <% @departments.each do|department|%>
  	<tr>
    	<td><%= department.name %></td>
    	<td>
    		<%= link_to("Delete",department_path(department), method: :delete, data: {confirm: 'Are you sure to delete?'},class: "btn btn-danger")%>  
    		<%= link_to("Update",edit_department_path(department), class: "btn btn-warning")%>  
    	</td>
  	</tr>
    <% end %>
    <%= link_to("Add New Department",new_department_path, class: "btn btn-primary")%>  
</table>

app/views/departments/new.html.erb
<h1> New Department</h1> 
<%= render 'form'%>

app/views/departments/show.html.erb
<h1> Show Department</h1>
	<div class="container">
	<div class="row">
	              <div class="col-md-7">
	                  <div class="crane-list-content">
	                      <div class="crane-title">
	                          <h3>Department Name: <%= @department.name %></h3>
	                      </div>
	                      <%= link_to('Back to all department list', departments_path, class: "btn btn-info") %> | 
	<%= link_to('Edit', edit_department_path, class: "btn btn-warning") %> |
	<%= link_to('Delete', department_path(@department),class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure to delete?'})%>
	                  </div>
	              </div>
	          </div>
	          </a>
	      </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studentmanagenemt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <%= yield %>
    <%= render 'partials/footer'%>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer style="text-align: center; padding: 5px; color: #e3f2fd blue lighten-5; background: #e1f5fe">
  <div style="color: #212121; footer-copyright text-center py-3">© 2019 Copyright:
    <a href="http://devbootstrap.com/"> DevBootstrap.com</a>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/students">Student Management</a>
    <ul class="nav navbar-nav">
    	<li class="active"><a href="/departments">Show Department List</a></li>
    </ul>
      </li>
      </ul>
    </ul>
  </div>
</nav>
  

  

app/views/students/_form.html.erb
<%= form_for(@student) do |f|%>
 <div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class= "row">
      <div class="col-md-3">
        <%= f.label :name , class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :name, autofocus: true , class: "form-control" %>
      </div>
    </div>
    </br>
    <div class= "row">
      <div class="col-md-3">
       <%= f.label :gender , class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= f.select(:gender, options_for_select(["Female", "Male"]), {}, { include_blank: true, class: 'form-control' }) %>
      </div>
    </div>
    </br>
    <div class="row">
      <div class="col-md-3">
        <%= f.label :address, class: "control-label" %>
      </div>
      <div class="col-md-6">     
        <%= f.text_field :address, autofocus: true , class: "form-control" %>
      </div>
    </div>
    </br>
    <div class="row">
      <div class="col-md-3">
        <%= f.label :department_id, class: "control-label" %><br/> 
      </div>
      <div class="col-md-6">  
        <%= f.select(:department_id, options_for_select(Department.all.map{|department| [department.name, department.id]}), {}, {include_blank: true, class: 'form-control' }) %>
      </div>
    </div>
    </br>  
    <div class="row">
      <%= f.submit "Save" ,class: "btn btn-success" %> |   
      <%=link_to "Cancel" , root_path%>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>
<% end %>

app/views/students/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" link_to(root_path)>Student Management</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
  

app/views/students/edit.html.erb
<h1>Editng Student Infomation</h1>
<%= flash[:notice]%>
 <%= render 'form'%>

app/views/students/index.html.erb
<h1>All Student List </h1>
<table>
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Address</th>
    <th>Department</th>
    <th>Setting</th>
  </tr>
  <%@students.each do |student| %>
  	<tr>
    	<td><%= student.name %></td>
    	<td><%= student.gender %></td>
    	<td><%= student.address %></td>
    	<td><%= student.department.try :name %></td>
    	<td>

    		<%= link_to("Edit",edit_student_path(student), class: "btn btn-warning")%>
    		<%= link_to("Delete",student_path(student), method: :delete, data: {confirm: 'Are you sure to delete?'}, class: "btn btn-danger")%>
    		<%= link_to("Details",student_path(student), class: "btn btn-info")%>
    	</td>  
  	</tr>
    <% end %>
    <%= link_to("Add New Student",new_student_path, class: "btn btn-primary")%>
</table>

app/views/students/new.html.erb
<h1>Add New Student</h1>
<%= render 'form' %>

app/views/students/show.html.erb
<div class="container">
    <div class="row">
        <div class=" col-lg-offset-3 col-lg-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="centered-text col-sm-offset-3 col-sm-6 col-md-offset-3 col-md-6 col-lg-offset-3 col-lg-6">
                                    <div itemscope="" itemtype="http://schema.org/Person">
                                        <h2> <span itemprop="name"><%=@student.name%></span></h2>
                                        <p itemprop="jobTitle"><%=@student.gender%></p>
                                        <p><span itemprop="affiliation"><%=@student.address%></span></p>
                                        <p>
                                            <i class="fa fa-map-marker"></i> <span itemprop="addressRegion"><%= @student.department.try :name %></span>
                                        </p>
                                        <%= link_to "Return to All Student List", root_path%>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>